name: Deploy Frontend Angular

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Adicionar chave SSH para acesso à VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar projeto Angular para a VM
        run: |
          scp -r ./ ${{ secrets.VM_USER }}@${{ secrets.GSP_VM_HOST }}:/home/${{ secrets.GCP_VM_USER }}/frontend/

      - name: Acessar VM e rodar docker build + run
        run: |
          ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_HOST }} << 'EOF'
            cd ~/frontend
            docker stop frontend || true
            docker rm frontend || true
            docker build -t angular-frontend .
            docker run -d --name frontend -p 80:80 angular-frontend
          EOF
